steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ycsb-image', '.' ]
- name: 'gcr.io/$PROJECT_ID/helm'
  id: Helm
  args:
  - 'template'
  - '.'
  - '>'
  - 'kubernetes.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=northamerica-northeast1'
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'
  - 'TILLERLESS=true'
images:
- 'gcr.io/$PROJECT_ID/ycsb-image'
