steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ycsb-image', '.' ]
- name: 'gcr.io/$PROJECT_ID/helm'
  id: Helm
  entrypoint: /bin/bash
  args: ['-c', 'helm template . > kubernetes.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=nosql-tests'
  - 'TILLERLESS=true'
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'kubernetes.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=nosql-tests'
images:
- 'gcr.io/$PROJECT_ID/ycsb-image'
