---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ycsb-deployment
  labels:
    app: ycsb
spec:
  selector:
    matchLabels:
      app: ycsb
  template:
    metadata:
      labels:
        app: ycsb
    spec:
      containers:
      - name: ycsb
        image: {{ include "image" . }}
        ports:
        - containerPort: 80
---